### ISSUE TITLE
핑퐁빌더 인증정보 노출됨

### ISSUE THREAD

**Issue by comjun04** [OHvrything/thingebotV2#1]
핑퐁빌더 인증정보가 노출되어 있습니다. 다른 사람이 악용할 수 있을 것 같습니다.

https://github.com/OHvrything/thingebotV2/blob/0e34a9828f0dbc76f485d0334828f9e4c42b4d5f/DiscordBot.py#L11-L12

**Comment by comjun04** [comment]
저거 처리하고 나서 인증토큰도 바꾸세요

**Comment by OHvrything** [comment]
허거걱! 네네 오늘 되면 처리 할게요.
